name: Build and GH Pages Deploy

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd example
    - run: npm install
    - run: npm run build
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        # Build directory to deploy
        build_dir: example/build
